fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cargo fmt --manifest-path ./src-tauri/Cargo.toml -- --check'
        language: rust
        files: \.rs$
        args: []

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash -c 'cargo check --manifest-path ./src-tauri/Cargo.toml --all'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources.
        entry: bash -c 'cargo clippy --manifest-path ./src-tauri/Cargo.toml --all-targets --all-features --tests --benches -- -D warnings'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Unit test for the project.
        entry: bash -c 'cargo test --manifest-path ./src-tauri/Cargo.toml --all-features'
        language: rust
        files: \.rs$
        pass_filenames: false

      - id: vitest
        name: Vitest
        entry: bash -c 'pnpm test -- --run'
        language: node
        files: \.ts$
        pass_filenames: false

      - id: lint-ts
        name: Front-end lint staged
        description: Lint the front-end code
        entry: bash -c 'pnpm lint-staged -v'
        language: node
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false
